### ISSUE TITLE
Get Error While Running From VS2019

### ISSUE THREAD

**Issue by Jim266** [docusign/sample-app-myclickwrap-csharp#10]
Tried to run the sample app from VS2019.  Kept getting error.
![image](https://user-images.githubusercontent.com/17112469/99443567-01f11580-28e9-11eb-8e77-384243216bc5.png)
Ran it in debug mode, it stopped at AuthenticateFromJWt()
![image](https://user-images.githubusercontent.com/17112469/99443319-a757b980-28e8-11eb-984e-cc14f4484cbe.png)
appsetting.json is set up like below. 
![image](https://user-images.githubusercontent.com/17112469/99443904-74fa8c00-28e9-11eb-9a4c-ce9335965351.png)

Can you shed light on what might go wrong?  Thanks.

**Comment by InbarGazit** [comment]
did you have the app redirect you to get consent for the user/account? this has to be done once when using JWT

**Comment by Jim266** [comment]
Thanks for prompt reply.  I just simply run the sample with update to the appsetting.json file.  Is there some other areas I need to change?

**Comment by InbarGazit** [comment]
Sorry Jim, this reply was lost and I didn't see it until now. Do you still need assistance with this?

**Comment by Jim266** [comment]
I'll be very happy if you can shed light on this.

**Comment by InbarGazit** [comment]
You would need to obtain consent for your app since you created your own Integration Key (IK).
This should include the right set of scopes.
Create a URL like below (update it with your IK and your URL which you configured for it.
https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id=YOURKEY&redirect_uri=YOURS

**Comment by Jim266** [comment]
Did you mean to replace the "AuthorizationEndpoint" in appsettings.json?

**Comment by InbarGazit** [comment]
no, I mean build the URL above and click it and sign in and consent to the app/IK

**Comment by Jim266** [comment]
excuse my stupidity.  I didn't quite understand your instructions.

I'm not sure what you meant by create a URL and I simply put the following in the address bar but was redirected to DocuSign log in with message"There are no redirect URIs registered with DocuSign.  Sounds like somewhere in admin portal I need to register an URI.  If this is true, would it be possible to I'm only testing it on my localhost?

https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id=**mykey**&redirect_uri=**adummyrul**

Anyway, thank you for your patience.

**Comment by InbarGazit** [comment]
you can use localhost, you an use any valid URL. You need to go to https://admindemo.docusign.com/authenticate?goTo=apiIntegratorKey and configure the IK to add this redirect URI to it

**Comment by Jim266** [comment]
I added redirect URI but when I run the it I got Unexpected PEM type.  See screenshot below.

![unnamed](https://user-images.githubusercontent.com/17112469/108907353-fbf98780-75ef-11eb-8f77-d8b968e20385.png)
![unnamed (1)](https://user-images.githubusercontent.com/17112469/108907366-fef47800-75ef-11eb-8573-94c3a250aa5c.png)

**Comment by InbarGazit** [comment]
ok, you're making progress. Now the issue is with the keypair. Did you generate and RSA keypair? and then copy the private one and save it into a file? it has to be done this way and then read from the code of the app

**Comment by InbarGazit** [comment]
Since this app has 3 separate projects, you need to copy appsettings.json and private.key for each of them (DocuSign.MyClickwrap.COVID19Waiver etc.)

**Comment by Jim266** [comment]
Thanks for your patience.  I updated all three appsetting.josn and the private in the root of each app but still getting same error mentioned earlier.

![image001 (1)](https://user-images.githubusercontent.com/17112469/108915192-834bf880-75fa-11eb-9dea-23c17f1f1cbb.png)

**Comment by InbarGazit** [comment]
ok,  your config file has RSAPrivateKeyFile as RSA.PEM and not private.key. So either rename all the files to RSA.PEM or change the appsettings.files to say private.key

**Comment by Jim266** [comment]
I hope i understood correctly.  I changed appsettting to use private.key but now getting no found error. 
![image001 (1)](https://user-images.githubusercontent.com/17112469/108918140-e2ac0780-75fe-11eb-98c4-e53a5a591ba2.png)

![image001](https://user-images.githubusercontent.com/17112469/108917766-4124b600-75fe-11eb-9641-3c36cf061a2e.png)
![unnamed](https://user-images.githubusercontent.com/17112469/108917779-46820080-75fe-11eb-9b31-cc3fcea3187e.png)

**Comment by InbarGazit** [comment]
Well, you need to match the name of the file (RSA.PEM or Private.key) to what you have in appsettings.json

**Comment by InbarGazit** [comment]
I think you just need to rename RSA.PEM to private.key

**Comment by Jim266** [comment]
No luck.  I renamed RSA.PEM to private.key and changed to value of "RSAPrivateKeyFile" in appsettings.json to private.key but getting "Unexpected PEM type"

**Comment by InbarGazit** [comment]
how did you generate the private key?

**Comment by Jim266** [comment]
using service integration option in admindemo.docusign.com/api-integration-key/ page

**Comment by InbarGazit** [comment]
Jim, I asked our support experts and they assure me this error means that the key is malformed or bad in some way.  It may be that you're saving it to file in the wrong way. I would create a new one, copy it to clipboard and paste into something like notepad, a simple editor that doesn't do any formatting and save it from there to private.key directly. That's how I usually do it and it works just fine.

**Comment by Jim266** [comment]
Thank you for your continuous support.  I deleted and recreated the key as per your suggestion.  Now I'm getting "Key does not exist" error.

**Comment by InbarGazit** [comment]
can I suggest a different approach for now? would you mind trying our Quickstart, select C# and see if you can get that working? you can switch the auth to JWT after you do to confirm that is working for you as well. I would like to understand if you are having issues unrelated to how you configure the key.
https://developers.docusign.com/docs/esign-rest-api/quickstart/

**Comment by Jim266** [comment]
That sounds a good idea and I have the same thought.  Will update you.

**Comment by Jim266** [comment]
The quick start generated me a C# solution.  I ran it but got the following error.  I check my DS profile and snipped you the URLs created by quick start.
![image002](https://user-images.githubusercontent.com/17112469/109188233-b5776a80-7760-11eb-9e84-7c9b636c0403.png)
![image001 (2)](https://user-images.githubusercontent.com/17112469/109188242-b8725b00-7760-11eb-98f8-ba74e1ace6a1.png)

**Comment by InbarGazit** [comment]
OK, I think there are some issues with the way your machine is set up that are beyond my ability to fix at this time. I'll need our customer support experts to assist you. I'll ask them to open a case and take it from here.

**Comment by InbarGazit** [comment]
https://www.danielcrabtree.com/blog/400/how-to-fix-iis-http-error-502-5-in-asp-net-core

**Comment by InbarGazit** [comment]
Do you have .NET Core installed?

**Comment by Jim266** [comment]
No, I don't.

**Comment by Jim266** [comment]
Going to install .net core.

**Comment by Jim266** [comment]
actually I do have .net core installed.  Just re-tried the app and still getting 502.5 error.
![image001 (3)](https://user-images.githubusercontent.com/17112469/109197288-cd53ec00-776a-11eb-8809-9880ea1ddd26.png)

**Comment by InbarGazit** [comment]
Sorry for dropping the ball on this Jim. Are you still interested in this issue?

**Comment by Jim266** [comment]
Thanks Inbar.  I just gave up.
