### ISSUE TITLE
style="overflow: hidden" doesn't get removed from body tag

### ISSUE THREAD

**Issue by nbicalcarata** [docusign/sample-app-myclickwrap-csharp#17]
After completing the document signing process via clickWrap I'm unable to scroll or interact with the page, this happens because the styling applied from modal to body tag isn't restored to original state. I've tried removing it by myself with onAgreed/onDeclined events but doing it this way triggers a modal rerender. Any help would be appreciated.

<img width="1019" alt="Captura de Pantalla 2021-05-03 a la(s) 8 53 56" src="https://user-images.githubusercontent.com/5392962/116885412-798fd400-abed-11eb-90d0-5a6d93643b5e.png">

**Comment by InbarGazit** [comment]
I'm not sure exactly at which point you have an issue. Any chance you can share a video? I just tried and it worked ok. Using Chrome browser. At the very end the page doesn't have much, it's pretty much empty page and you have to click the top left if you want to go back, but not sure you go that far.

**Comment by nbicalcarata** [comment]
Hi, the issue is that this style overflow hidden appears in my app too, so it blocks any scrolling and the interaction with the page is broken. In my use case, clickWrap it's and intermediate step in my app flow, but in the demo app it's not noticeable. I'ill try to make sample video to show you, thanks or your attention!

**Comment by nbicalcarata** [comment]
https://user-images.githubusercontent.com/5392962/116910038-a4d4ec00-ac0a-11eb-85c7-938596b86947.mov

**Comment by InbarGazit** [comment]
The issue you are showing seems to be on your own app code. I thought you had an issue with this application. Can you reproduce the problem when you go to http://myclickwrap.sampleapps.docusign.com/ ?

**Comment by nbicalcarata** [comment]
Yes, it's happenning the same issue with nondisclosure, and covid sample apps, the first screenshot it's taken from my testing there

**Comment by InbarGazit** [comment]
Are you available for a zoom call?

**Comment by nbicalcarata** [comment]
Shure, I'm available right now

**Comment by InbarGazit** [comment]
Sorry, if you are still available at 3pm PDT (6PM EDT) - we can go into Zoom at https://docusign.zoom.us/j/94543942622?pwd=VmN4U1BoTldtYm90U1UrZktSVjJtZz09&from=addon

**Comment by nbicalcarata** [comment]
No problem, thanks!, I'll be there

**Comment by InbarGazit** [comment]
You can join now, I'm in there...

**Comment by nbicalcarata** [comment]
I'm closing this since it looks it's already solved by an update, and the suggested workaround it's not longer needed, thanks for your help. :)

```
setTimeout(() => {
  document.body.style.overflow = ''
  handleOnDeclined()
}, 1000)
```
